# docker-compose.yml
version: '3'

services:

  postgres:
    container_name: postgres
    # Official Postgres image from DockerHub (we use the last version)
    image: 'postgres:13'
    # limit the memory and cpu usage
    # mem_limit: 512m
    # mem_reservation: 128M
    # cpus: 0.5
    volumes:
      - ./docker_shared_folder/postgres_data:/var/lib/postgresql/data
    # By default, a Postgres database is running on the 5432 port.
    # If we want to access the database from our computer (outside the container),
    # we must share the port with our computer's port.
    # The syntax is [port we want on our machine]:[port we want to retrieve in the container]
    # Note: You are free to change your computer's port,
    # but take into consideration that it will change the way
    # you are connecting to your database.
    ports:
      - 5433:5433
    environment:
      - POSTGRES_DB=postgres # The PostgreSQL default database (automatically created at first launch)
      - POSTGRES_USER=postgres # The PostgreSQL user (useful to connect to the database)
      - POSTGRES_PASSWORD=postgres # The PostgreSQL password (useful to connect to the database)
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    command: "-p 5433" # Change the default port of the database
    networks:
      coder_net:
        ipv4_address: 172.30.1.1

  pgadmin:
      container_name: pgadmin4
      image: dpage/pgadmin4:7
      restart: always
      environment:
          PGADMIN_DEFAULT_EMAIL: admin@admin.com
          PGADMIN_DEFAULT_PASSWORD: admin
      ports:
          - "10080:80"

  mongo:
    image: mongo:4.4.21
    restart: unless-stopped
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./docker_shared_folder/mongo_data:/data/db
    networks:
      coder_net:
        ipv4_address: 172.30.1.2

  mongo-express:
    image: mongo-express:0.54
    restart: unless-stopped
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
    networks:
      coder_net:
        ipv4_address: 172.30.1.3
  
networks:
  coder_net: # Name of the network
    ipam: # IP Address Management
      driver: default
      config:
        - subnet: 172.30.0.0/16 # Subnet
        # 172.30.0.0 is the default subnet for docker
        # 16 is the number of bits used for the network